### ISSUE TITLE
Exclude useless min.js from bower.json

### ISSUE THREAD

**Issue by geobourazanas** [cpettitt/graphlib#37]
Can you please exclude .min.js from the main parameter inside bower.json? I think is just duplicate to use both versions there.

```javascript
"main": [
    "dist/graphlib.core.js",
    "dist/graphlib.core.min.js"
  ]
```

**Comment by yonatang** [comment]
+1
Quoting from https://www.npmjs.com/package/bower-archive: 
> There should only be at most one file per file type in the main list. So only one .js or .css.
