### ISSUE TITLE
Persistent/immutable?

### ISSUE THREAD

**Issue by sdboyer** [cpettitt/graphlib#41]
i saw you note over in facebook/immutable-js#35 that you're working on a persistent graph lib. i've need of such a thing :) is that work here, or supposed to be here eventually?

**Comment by cpettitt** [comment]
I played around with the idea here: https://github.com/cpettitt/pgraph.

It's been a while, but I recall that writes were too slow to be usable for my purposes (graph layout). I just tried the project with hamt (2 - 3.5x faster than immutable when I tested 9 months ago) and found that graphlib is still ~10x faster on writes. It's possible that immutable performs much better now and this is a more reasonable path to explore, but I have too many projects invested in the mutable path now.

**Comment by sdboyer** [comment]
ahh yeah, for me the immut graph isn't being used to run a simulation or layout engine, so lower write speed is acceptable.  a HAMT makes sense, though my data guarantees a single unique integer identifier space across `V`, so i may try to roll something based on [intmaps](http://ittc.ku.edu/~andygill/papers/IntMap98.pdf). but i'll have a look at your other lib - thanks!
