### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by ValentinTrinque** [cpettitt/graphlib#43]
Hi,

I am currently working on a JavaScript library using graphlib. I use Typescript to enhance the development.

What about add a typescript support ?

You can support Typescript by defining a ["definition file"](http://www.typescriptlang.org/Handbook#writing-dts-files) which expose the external library API. It mainly exists for compile time check.

**Comment by cpettitt** [comment]
I would be happy to take a Typescript definition as a contribution. The API is stable at this point as we're into 1.x versions.

**Comment by ValentinTrinque** [comment]
Cool ! Working on it then !

**Comment by ValentinTrinque** [comment]
Hey! Just coming for news. I finished the job but I want to test it in a real project to be sure that's working.

Come back to you in the next few days.

**Comment by danvk** [comment]
FYI I've sent out a PR to add TS definitions for graphlib to DefinitelyTyped.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10849

**Comment by danvk** [comment]
... and that PR was merged. This issue can be closed now.

```
typings install --global dt~graphlib
```

**Comment by cpettitt** [comment]
Thanks @danvk!
