### ISSUE TITLE
Get nodes by label name

### ISSUE THREAD

**Issue by mdehollander** [cpettitt/graphlib#44]
Hi,

I would like to retrieve specific nodes by the label they have. In the API I don't directly see how to do this. I am looking for something like graph.getNode(label). 
In the end I would like to use graphlib to parse a dot file and to visualize it with cola.js. By retrieving specific nodes I aim to make groups in order to visualize the graph like this: http://marvl.infotech.monash.edu/webcola/examples/smallgroups.html

**Comment by cpettitt** [comment]
There is no way to get a node by label, since the type of the label can be anything and there is no guarantee that the same label will not be used by multiple nodes. It sounds like you do have a guaranteed unique string representation for each node label. In that case, you can use an object to map the label to the node's id, which is guaranteed to be unique.

```js
var g = new Graph();
g.setNode(1, "foo");
g.setNode(2, "bar");

var mapping = {};
g.nodes().forEach(function(u) { mapping[g.node(u)] = u; });

console.log(mapping.foo); // prints '1'
console.log(mapping.bar); // prints '2'
```

**Comment by kavuri** [comment]
I am hitting a similar (though slightly different) use case of trying to get a successor node with a given label. I have the following graph representation:

```
g.setNode("1", "foo");
g.setNode("2", "bar");
g.setNode("3", "xyz");
g.setNode("4", "pqr");
g.setEdge("1", "2", {label:"time"});
g.setEdge("1", "3", {label: "space"});
g.setEdge("1", "4", {label":"cont"});
```

I was thinking of something like,
`const c = g.getSuccessor("1", {label:"time"}); // returns "2"`

The signature would be something like `g.getSuccessor(<nodeName>, <edgeLabel>)`

I understand that the edges are unique, but maybe leave it to the API user?
