### ISSUE TITLE
Inconsistent conversion of node IDs to strings

### ISSUE THREAD

**Issue by seren** [cpettitt/graphlib#47]
Node IDs seem to be stored internally as strings and any integer ID inputs are automatically converted to strings:

    g=new graphlib.Graph();
    g.setNode(1);
    g.setNode('2');
    g.hasNode('1');  // true
    g.hasNode(2);    // true

This is useful, since you can store node values in a standard array data-structure, but use the array indices as graph node IDs. This gives the code a lot of flexibility and allows you to operate on your node values indepedently of when you build the graph.

However, there is a bug where certain integer IDs don't get properly converted to strings:

    g=new graphlib.Graph({ directed: false});
    g.setNode(2);
    g.setNode(9);
    g.setNode(10);
    g.setEdge(2,9);
    g.setEdge(9,10);
    g.setEdge(10,2);

    g.hasEdge('2','9') // true
    g.hasEdge('9','10') // true
    g.hasEdge('10','2') // true

    g.hasEdge(2,9) // true
    g.hasEdge(9,10) // false, unexpected behavior
    g.hasEdge(10,2) // false, unexpected behavior

Another example:

    // Works: [1,10]
    a=graphlib.json.read(JSON.parse('{"options":{"directed":false},"nodes":[{"v":"1"},{"v":"10"}],"edges":[{"v":"10","w":"1"}]}'));
    a.hasEdge('1','10') // true
    a.hasEdge(1,10) // true, expected behavior

    // Fails: [9,88]
    a=graphlib.json.read(JSON.parse('{"options":{"directed":false},"nodes":[{"v":"9"},{"v":"88"}],"edges":[{"v":"88","w":"9"}]}'));
    a.hasEdge('9','88') // true
    a.hasEdge(9,88) // false, unexpected behavior

I haven't had time to look through the graphlib source. It's very odd behavior that doesn't seem to depend on the order of edge IDs, or any particular value of ID.

**Comment by cpettitt** [comment]
Thanks for the detailed repro steps. I was able to reproduce this and know what the issue is. I should be able to get a fix up shortly.

**Comment by seren** [comment]
Thanks for the quick fix!
