### ISSUE TITLE
non-string nodes

### ISSUE THREAD

**Issue by timoxley** [cpettitt/graphlib#48]
Perhaps consider using an ES6 Map as the underlying storage for nodes so they can be other datatypes other than Strings.

e.g.

```js
var user = {
  name: 'Bob'
}
graph.addNode(user)
```

**Comment by stephanos** [comment]
I have a similar need. I'd love to associate any data with a node. My use case is I'm writing a dependency injection container that manages components and their connections with `graphlib`. Currently I need separate map to match node id and actual data.

**Comment by cpettitt** [comment]
You can attach arbitrary data to a node via its label. See [setNode](https://github.com/cpettitt/graphlib/wiki/API-Reference#setNode) and [node](https://github.com/cpettitt/graphlib/wiki/API-Reference#node).
