### ISSUE TITLE
Please Update Wiki with Instructions for Browser Use

### ISSUE THREAD

**Issue by gardner** [cpettitt/graphlib#50]
It is unclear how to use graphlib.js in a browser. It would be great to update the wiki with instructions on how to use it within a browser.

* Attempting to call `require` reasonably throws an undefined error.
* Attempting to load the js and instantiate `Graph` throws an undefined error.
* Attempting to instantiate `Graph` in body onLoad handler throws an undefined error.

**Steps to reproduce:**

Download `graphlib.js` locally:

    wget "https://cpettitt.github.io/project/graphlib/latest/graphlib.js"

Create index.html:

    <!DOCTYPE html>
    <html>
    <head>
      <title>graphlib test</title>
      <script src="graphlib.js"></script>
    </head>

    <body>
        graphlib
      <script>
        var g = new Graph();
        console.log(g);
      </script>

    </body>

    </html>

Observe error:

    Uncaught ReferenceError: Graph is not defined

**Comment by stevebarry** [comment]
Hi Gardner,
I suspect you've figured this out yourself at this stage, but I've updated the Wiki with browser instructions as you've suggested. You need to add the graphlib prefix so var g = new graphlib.Graph();
Regards,
Steve.

**Comment by gardner** [comment]
thanks @stevebarry

**Comment by cpettitt** [comment]
Thanks for the wiki update @stevebarry!
