### ISSUE TITLE
Move to ES6 (aka ES2015)

### ISSUE THREAD

**Issue by ValentinTrinque** [cpettitt/graphlib#51]
Hi,

Is there any plan for Grpahli to move to the next update of JavaScript such as ES6 ?

Thanks.

**Comment by cpettitt** [comment]
What kind of features would you want to use from ES6? Are you talking about the API or the internals?

**Comment by ValentinTrinque** [comment]
Actually, just moving the code to the new syntax and features. I think it
would be cool to keep graphlib up to date.

It could also be the moment to review the API. Not because it's bad... In
my mind, it's satisfying, but we could look for improvments.

I would be very please to participate.

What do you think ?

**Comment by cpettitt** [comment]
I'm OK taking patches that use ES6 code. Ultimately the ES6 should be transpiled down to ES5 before publishing it. That could either be done via the makefile or prepublish script in npm.

I do want to ensure that non-functional changes don't cause performance regressions. I spent a fair amount of time tuning performance in graphlib.

**Comment by ValentinTrinque** [comment]
Sounds ok.

Thanks for the information.
