### ISSUE TITLE
It's impossible to get all edges at once for {v: a, w: b} when multigraph:true

### ISSUE THREAD

**Issue by sprilukin** [cpettitt/graphlib#53]
Lets suppose i've created a mutligraph and created two edges between same nodes:

```js
var g = new Graph({ multigraph: true });
g.setEdge("a", "b", "edge1-label", "edge1");
g.setEdge("a", "b", "edge2-label", "edge2");
```

now i want to retrieve all edges between these two nodes, for example:

```js
g.edge({ v: "a", w: "b" }) 
```
i would expect this method to return something like: 
```js
{"edge1": "edge1-label", "edge2": "edge2-label"}
```

But it only returns the first edge value.

**Comment by cpettitt** [comment]
This should help: https://github.com/cpettitt/graphlib/wiki/API-Reference#nodeEdges.

**Comment by sprilukin** [comment]
Yes this will works, but this method has two drawbacks:
1. Does not respect direction
2. takes ```O(|E|)```

I've implemented this in other way:

```js
var g = new Graph(); //multigraph: false

//adding first edge - with id "edge1"
g.setEdge("a", "b", {"edge1": {otherInfo: "..."}});

//get info about all edges between "a", "b"
var edgeInfo = g.edge("a", "b"); // -> {"edge1": {otherInfo: "..."}}

//adding second edge
edgeInfo["edge2"] = {"otherInfo": "..."}

//check all edges between a, b:
var edgeInfo = g.edge("a", "b"); // -> {"edge1": {otherInfo: "..."}, "edge2": {otherInfo: ""}}
```

This works, but it also has drawbacks:
1. I need to manually handle edges object
2. Algorithms such as dijkstra will not work correctly since they do not know about that surrogate edges.

**Comment by cpettitt** [comment]
https://github.com/cpettitt/graphlib/wiki/API-Reference#inEdges and https://github.com/cpettitt/graphlib/wiki/API-Reference#outEdges give you directionality. Storing multi-edges directly in the label will have the same worst case time complexity as the above. In practice the above might be faster - it'd have to be measured.

**Comment by sprilukin** [comment]
Well i thought that this operation:

```js
//check all edges between a, b:
var edgeInfo = g.edge("a", "b"); // -> {"edge1": {otherInfo: "..."}, "edge2": {otherInfo: ""}}
```

takes constant ```O(1)``` time

What is the worst case you are talking about?

**Comment by cpettitt** [comment]
@sprilukin You're right, the access itself is going to take constant time. The linear time complexity comes in when you try to scan the list. Your approach is fine, but you may or may not get a speed up in practice to compensate for having to carry additional traversal logic along with the graph (e.g. `edgeFn`).
