### ISSUE TITLE
Is that possible to design a API that generating graph by reading edge list file (txt, or csv)

### ISSUE THREAD

**Issue by lvyachao** [cpettitt/graphlib#54]
Since there is so many dataset (edge lists) available online but stored with txt or csv format, I think it will be useful if there is a API support this function.

**Comment by cpettitt** [comment]
You can load from any format you like. There are a couple of parsers available that you could use as examples for parsing your own format: lib/json.js in this repo, and graphlib-dot (separate repo). The latter involves a much more complex language (DOT), and uses a peg-js parser.
