### ISSUE TITLE
Directed property

### ISSUE THREAD

**Issue by fabiovalse** [cpettitt/graphlib#68]
I'm setting the _directed_ property to false in order to make my graph undirected. However, a problem occurs when I run the _dijkstra_ algorithm.

If I set the property to true (that is the default) it returns as expected the distances of nodes taking into account the direction of the edges.

If I set the property to false it returns the distances of nodes taking into account only the reverse direction of the original edges, instead of ignoring the direction altogether.

**Comment by cpettitt** [comment]
Are you using `nodeEdges` or `outEdges` (the default) for the edge function in `dijkstra`? If you want to walk it with an undirected graph you should use the former - `outEdges` is us undefined for an undirected graph:  https://github.com/cpettitt/graphlib/wiki/API-Reference#outEdges

**Comment by fabiovalse** [comment]
Thank you, I was using the default (outEdges) and now I get all the edges.

Maybe if I can suggest you an improvement for your wiki, it would be good to add something like:

_"If you need to run Dijkstra on an undirected graph it is necessary to use g.nodeEdges in the edge function."_

in the paragraph about _edgeFn(v)_ in the [dijkstra algorithm documentation](https://github.com/cpettitt/graphlib/wiki/API-Reference#alg-dijkstra).
