### ISSUE TITLE
Is there a "recommended" way of cloning a graph? (is this on roadmap?)

### ISSUE THREAD

**Issue by justin-calleja** [cpettitt/graphlib#69]
Is there a "recommended" way of cloning a graph?

Will cloning be added to the API at some point?

Thanks

**Comment by coli** [comment]
If you use the graphlib-dot library you can just parse it from json back and forth multiple times to get multiple graphs

**Comment by justin-calleja** [comment]
@coli thanks. I'm closing the issue but have not confirmed your solution as I'm not even sure in which "project" I needed it.

Thanks again
